baseURL = "https://festive-spence-7a91ca.netlify.com/"
languageCode = "en-us"
title = "Graduation Project"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Jimmy Zheng"
    description = "Cloud Hosting"
    githubUsername = "#"
    backgroundColor = "white"
    font = "Ubuntu" # should match the name on Google Fonts!

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/reflection/"
    name = "Reflections"
    weight = 2

[[menu.main]]
    url = "/research/"
    name = "Research Paper"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

#[[menu.icon]]
#    url = "mailto:me@example.com"
#    name = "envelope-o"
#    weight = 1

#[[menu.icon]]
#    url = "https://github.com/username/"
#    name = "github"
#    weight = 2

#[[menu.icon]]
#    url = "https://twitter.com/username/"
#    name = "twitter"
#    weight = 3

#[[menu.icon]]
#    url = "https://www.linkedin.com/in/username/"
#    name = "linkedin"
#    weight = 4

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "stack-overflow"
#   weight = 5
